name: mkernel documentation
on:
  workflow_run:
    workflows: ["mkernel"]
    branches: [main]
    types: completed
jobs:
  documentation:
    name: Deploy documentation
    strategy:
      matrix:
        ocaml-version: [5.3.0]
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: |
            *.opam
      - name: Install dependencies
        run: |
          opam install --deps-only -t mkernel
          opam install odoc
      - name: Build documentation
        run: opam exec -- dune build @doc-new -p mkernel
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc_new/html/docs/
